# _config.dev.yml — local-only overrides
# -----------------------------------------------------------------------------
# Purpose: Local development overrides for Jekyll/al-folio.
# How it works: Jekyll merges multiple config files. When you run:
#   bundle exec jekyll serve --livereload --incremental --config _config.yml,_config.dev.yml
# settings in _config.dev.yml override matching keys from _config.yml.
#
# Merge rules to remember:
# - Scalars (strings/numbers/bools): replaced by the later file.
# - Maps (objects): merged key-by-key; later values win.
# - Arrays (lists, e.g., `plugins:`): REPLACED entirely by the later file.
#   => Don’t put `plugins:` here unless you intend to replace the main list.
#
# Why this file: Speeds up local builds and avoids Windows issues by disabling
# heavy/minifying/image steps you don’t need while previewing.
#
# Tip: Keep this file committed so teammates get the same dev behavior, or add
# it to .gitignore if you prefer it to stay local-only.
# -----------------------------------------------------------------------------

# Serve from localhost, no subpath
url: "http://127.0.0.1:4000"
baseurl: ""

# Replace plugin list for dev (omit terser, jekyll-minifier, jekyll-imagemagick)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-toc
  - jekyll-tabs
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-email-protect
  - jekyll-archives-v2
  - jekyll-twitter-plugin
  - jekyll-regex-replace
  - jekyll-jupyter-notebook
  - jemoji

# Optional: exclude extra stuff from the dev build (keeps the watcher quieter)
exclude:
  - node_modules
  - vendor
  - tmp
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - README.md
  - CUSTOMIZE.md
  - Gemfile.lock
  - package-lock.json
  - docker
  - scripts


# Optional: make sure we don't accidentally produce production-y output locally
# (Jekyll sets JEKYLL_ENV=development for `serve` anyway, but this is a reminder)
# environment: development

# -----------------------------------------------------------------------------------------
# Live Preview Command
# -----------------------------------------------------------------------------------------
# 
# bundle exec jekyll serve --livereload --incremental --config _config.yml,_config.dev.yml